// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.2
// source: proto/yapshrtnr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Long  string `protobuf:"bytes,2,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *URL) Reset() {
	*x = URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *URL) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type Short struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *Short) Reset() {
	*x = Short{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Short) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Short) ProtoMessage() {}

func (x *Short) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Short.ProtoReflect.Descriptor instead.
func (*Short) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{1}
}

func (x *Short) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type Long struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *Long) Reset() {
	*x = Long{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Long) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Long) ProtoMessage() {}

func (x *Long) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Long.ProtoReflect.Descriptor instead.
func (*Long) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{2}
}

func (x *Long) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int32 `protobuf:"zigzag32,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int32 `protobuf:"zigzag32,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long    string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
	Deleted bool   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *GetResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RequestBatchURLs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs []*RequestBatchURLsInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
}

func (x *RequestBatchURLs) Reset() {
	*x = RequestBatchURLs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchURLs) ProtoMessage() {}

func (x *RequestBatchURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchURLs.ProtoReflect.Descriptor instead.
func (*RequestBatchURLs) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{5}
}

func (x *RequestBatchURLs) GetInputs() []*RequestBatchURLsInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ResponseBatchURLs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outputs []*ResponseBatchURLsOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *ResponseBatchURLs) Reset() {
	*x = ResponseBatchURLs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBatchURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBatchURLs) ProtoMessage() {}

func (x *ResponseBatchURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBatchURLs.ProtoReflect.Descriptor instead.
func (*ResponseBatchURLs) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseBatchURLs) GetOutputs() []*ResponseBatchURLsOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type RequestDeleteBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorts []*Short `protobuf:"bytes,1,rep,name=shorts,proto3" json:"shorts,omitempty"`
}

func (x *RequestDeleteBatch) Reset() {
	*x = RequestDeleteBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteBatch) ProtoMessage() {}

func (x *RequestDeleteBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteBatch.ProtoReflect.Descriptor instead.
func (*RequestDeleteBatch) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{7}
}

func (x *RequestDeleteBatch) GetShorts() []*Short {
	if x != nil {
		return x.Shorts
	}
	return nil
}

type ResponseGetURLsByUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*URL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ResponseGetURLsByUser) Reset() {
	*x = ResponseGetURLsByUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetURLsByUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetURLsByUser) ProtoMessage() {}

func (x *ResponseGetURLsByUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetURLsByUser.ProtoReflect.Descriptor instead.
func (*ResponseGetURLsByUser) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseGetURLsByUser) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type RequestBatchURLsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long          string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *RequestBatchURLsInput) Reset() {
	*x = RequestBatchURLsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBatchURLsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBatchURLsInput) ProtoMessage() {}

func (x *RequestBatchURLsInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBatchURLsInput.ProtoReflect.Descriptor instead.
func (*RequestBatchURLsInput) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RequestBatchURLsInput) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *RequestBatchURLsInput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ResponseBatchURLsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short         string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *ResponseBatchURLsOutput) Reset() {
	*x = ResponseBatchURLsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yapshrtnr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBatchURLsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBatchURLsOutput) ProtoMessage() {}

func (x *ResponseBatchURLsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yapshrtnr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBatchURLsOutput.ProtoReflect.Descriptor instead.
func (*ResponseBatchURLsOutput) Descriptor() ([]byte, []int) {
	return file_proto_yapshrtnr_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ResponseBatchURLsOutput) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *ResponseBatchURLsOutput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_proto_yapshrtnr_proto protoreflect.FileDescriptor

var file_proto_yapshrtnr_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74,
	0x6e, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2f, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x22, 0x1d, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x22,
	0x1a, 0x0a, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x39, 0x0a, 0x0d, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68,
	0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x55, 0x52, 0x4c, 0x73, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x73, 0x1a, 0x42, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x3d, 0x0a,
	0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x2e, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x45, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x61, 0x70, 0x73,
	0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47,
	0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x79, 0x61, 0x70,
	0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x32, 0xd0, 0x03, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x38,
	0x0a, 0x06, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x42, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55,
	0x52, 0x4c, 0x12, 0x10, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x1a, 0x16, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07,
	0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x0f, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72,
	0x74, 0x6e, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x1a, 0x10, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68,
	0x72, 0x74, 0x6e, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x44, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74,
	0x6e, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c,
	0x73, 0x12, 0x1b, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x1a, 0x1c,
	0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x4a, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x49, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55,
	0x52, 0x4c, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x20, 0x2e, 0x79, 0x61, 0x70, 0x73, 0x68, 0x72, 0x74, 0x6e, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_yapshrtnr_proto_rawDescOnce sync.Once
	file_proto_yapshrtnr_proto_rawDescData = file_proto_yapshrtnr_proto_rawDesc
)

func file_proto_yapshrtnr_proto_rawDescGZIP() []byte {
	file_proto_yapshrtnr_proto_rawDescOnce.Do(func() {
		file_proto_yapshrtnr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_yapshrtnr_proto_rawDescData)
	})
	return file_proto_yapshrtnr_proto_rawDescData
}

var file_proto_yapshrtnr_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_yapshrtnr_proto_goTypes = []interface{}{
	(*URL)(nil),                     // 0: yapshrtnr.URL
	(*Short)(nil),                   // 1: yapshrtnr.Short
	(*Long)(nil),                    // 2: yapshrtnr.Long
	(*StatsResponse)(nil),           // 3: yapshrtnr.StatsResponse
	(*GetResponse)(nil),             // 4: yapshrtnr.GetResponse
	(*RequestBatchURLs)(nil),        // 5: yapshrtnr.RequestBatchURLs
	(*ResponseBatchURLs)(nil),       // 6: yapshrtnr.ResponseBatchURLs
	(*RequestDeleteBatch)(nil),      // 7: yapshrtnr.RequestDeleteBatch
	(*ResponseGetURLsByUser)(nil),   // 8: yapshrtnr.ResponseGetURLsByUser
	(*RequestBatchURLsInput)(nil),   // 9: yapshrtnr.RequestBatchURLs.input
	(*ResponseBatchURLsOutput)(nil), // 10: yapshrtnr.ResponseBatchURLs.output
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_proto_yapshrtnr_proto_depIdxs = []int32{
	9,  // 0: yapshrtnr.RequestBatchURLs.inputs:type_name -> yapshrtnr.RequestBatchURLs.input
	10, // 1: yapshrtnr.ResponseBatchURLs.outputs:type_name -> yapshrtnr.ResponseBatchURLs.output
	1,  // 2: yapshrtnr.RequestDeleteBatch.shorts:type_name -> yapshrtnr.Short
	0,  // 3: yapshrtnr.ResponseGetURLsByUser.urls:type_name -> yapshrtnr.URL
	11, // 4: yapshrtnr.Shortener.PingDB:input_type -> google.protobuf.Empty
	1,  // 5: yapshrtnr.Shortener.GetURL:input_type -> yapshrtnr.Short
	2,  // 6: yapshrtnr.Shortener.PostURL:input_type -> yapshrtnr.Long
	11, // 7: yapshrtnr.Shortener.GetInternalStats:input_type -> google.protobuf.Empty
	5,  // 8: yapshrtnr.Shortener.PostBatchURLs:input_type -> yapshrtnr.RequestBatchURLs
	7,  // 9: yapshrtnr.Shortener.DeleteBatchByUser:input_type -> yapshrtnr.RequestDeleteBatch
	11, // 10: yapshrtnr.Shortener.GetURLsByUser:input_type -> google.protobuf.Empty
	11, // 11: yapshrtnr.Shortener.PingDB:output_type -> google.protobuf.Empty
	4,  // 12: yapshrtnr.Shortener.GetURL:output_type -> yapshrtnr.GetResponse
	1,  // 13: yapshrtnr.Shortener.PostURL:output_type -> yapshrtnr.Short
	3,  // 14: yapshrtnr.Shortener.GetInternalStats:output_type -> yapshrtnr.StatsResponse
	6,  // 15: yapshrtnr.Shortener.PostBatchURLs:output_type -> yapshrtnr.ResponseBatchURLs
	11, // 16: yapshrtnr.Shortener.DeleteBatchByUser:output_type -> google.protobuf.Empty
	8,  // 17: yapshrtnr.Shortener.GetURLsByUser:output_type -> yapshrtnr.ResponseGetURLsByUser
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_yapshrtnr_proto_init() }
func file_proto_yapshrtnr_proto_init() {
	if File_proto_yapshrtnr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_yapshrtnr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Short); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Long); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatchURLs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBatchURLs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetURLsByUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBatchURLsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yapshrtnr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBatchURLsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_yapshrtnr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yapshrtnr_proto_goTypes,
		DependencyIndexes: file_proto_yapshrtnr_proto_depIdxs,
		MessageInfos:      file_proto_yapshrtnr_proto_msgTypes,
	}.Build()
	File_proto_yapshrtnr_proto = out.File
	file_proto_yapshrtnr_proto_rawDesc = nil
	file_proto_yapshrtnr_proto_goTypes = nil
	file_proto_yapshrtnr_proto_depIdxs = nil
}
